/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
/* tslint:disable */

import '@stencil/core';

import '@ionic/core';
import 'ionicons';




declare global {
  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}

  namespace StencilComponents {

    interface PageActionSheet {

    }

    interface PageAlert {

    }

    interface PageBadge {

    }

    interface PageButton {

    }

    interface PageCard {

    }

    interface PageCheckbox {

    }

    interface ComponentPreview {

    }

    interface PageDatetime {

    }

    interface PageFab {

    }

    interface PageGrid {

    }

    interface AppList {
      'items': any[];
    }

    interface PageInfiniteScroll {

    }

    interface PageInput {

    }

    interface PageList {

    }

    interface PageLoading {

    }

    interface HomePage {

    }

    interface PageMenu {

    }

    interface ProfilePage {

    }

    interface ModalPage {
      'char': string;
    }

    interface PageModal {

    }

    interface NavDetails {
      'tech': any;
    }

    interface NavHome {

    }

    interface PageNav {

    }

    interface PageIndex {
      'pages': any[];
    }

    interface PopoverPage {
      'contentEl': HTMLElement;
    }

    interface PagePopover {

    }

    interface PageRange {

    }

    interface PageRefresher {

    }

    interface PageSearchbar {

    }

    interface PageSelect {

    }

    interface PageSlides {

    }

    interface PageSpinner {

    }

    interface PageTabs {

    }

    interface PageToast {

    }

    interface PageVirtualScroll {

    }
  }


    interface HTMLPageActionSheetElement extends StencilComponents.PageActionSheet, HTMLStencilElement {}

    var HTMLPageActionSheetElement: {
      prototype: HTMLPageActionSheetElement;
      new (): HTMLPageActionSheetElement;
    };
    

    interface HTMLPageAlertElement extends StencilComponents.PageAlert, HTMLStencilElement {}

    var HTMLPageAlertElement: {
      prototype: HTMLPageAlertElement;
      new (): HTMLPageAlertElement;
    };
    

    interface HTMLPageBadgeElement extends StencilComponents.PageBadge, HTMLStencilElement {}

    var HTMLPageBadgeElement: {
      prototype: HTMLPageBadgeElement;
      new (): HTMLPageBadgeElement;
    };
    

    interface HTMLPageButtonElement extends StencilComponents.PageButton, HTMLStencilElement {}

    var HTMLPageButtonElement: {
      prototype: HTMLPageButtonElement;
      new (): HTMLPageButtonElement;
    };
    

    interface HTMLPageCardElement extends StencilComponents.PageCard, HTMLStencilElement {}

    var HTMLPageCardElement: {
      prototype: HTMLPageCardElement;
      new (): HTMLPageCardElement;
    };
    

    interface HTMLPageCheckboxElement extends StencilComponents.PageCheckbox, HTMLStencilElement {}

    var HTMLPageCheckboxElement: {
      prototype: HTMLPageCheckboxElement;
      new (): HTMLPageCheckboxElement;
    };
    

    interface HTMLComponentPreviewElement extends StencilComponents.ComponentPreview, HTMLStencilElement {}

    var HTMLComponentPreviewElement: {
      prototype: HTMLComponentPreviewElement;
      new (): HTMLComponentPreviewElement;
    };
    

    interface HTMLPageDatetimeElement extends StencilComponents.PageDatetime, HTMLStencilElement {}

    var HTMLPageDatetimeElement: {
      prototype: HTMLPageDatetimeElement;
      new (): HTMLPageDatetimeElement;
    };
    

    interface HTMLPageFabElement extends StencilComponents.PageFab, HTMLStencilElement {}

    var HTMLPageFabElement: {
      prototype: HTMLPageFabElement;
      new (): HTMLPageFabElement;
    };
    

    interface HTMLPageGridElement extends StencilComponents.PageGrid, HTMLStencilElement {}

    var HTMLPageGridElement: {
      prototype: HTMLPageGridElement;
      new (): HTMLPageGridElement;
    };
    

    interface HTMLAppListElement extends StencilComponents.AppList, HTMLStencilElement {}

    var HTMLAppListElement: {
      prototype: HTMLAppListElement;
      new (): HTMLAppListElement;
    };
    

    interface HTMLPageInfiniteScrollElement extends StencilComponents.PageInfiniteScroll, HTMLStencilElement {}

    var HTMLPageInfiniteScrollElement: {
      prototype: HTMLPageInfiniteScrollElement;
      new (): HTMLPageInfiniteScrollElement;
    };
    

    interface HTMLPageInputElement extends StencilComponents.PageInput, HTMLStencilElement {}

    var HTMLPageInputElement: {
      prototype: HTMLPageInputElement;
      new (): HTMLPageInputElement;
    };
    

    interface HTMLPageListElement extends StencilComponents.PageList, HTMLStencilElement {}

    var HTMLPageListElement: {
      prototype: HTMLPageListElement;
      new (): HTMLPageListElement;
    };
    

    interface HTMLPageLoadingElement extends StencilComponents.PageLoading, HTMLStencilElement {}

    var HTMLPageLoadingElement: {
      prototype: HTMLPageLoadingElement;
      new (): HTMLPageLoadingElement;
    };
    

    interface HTMLHomePageElement extends StencilComponents.HomePage, HTMLStencilElement {}

    var HTMLHomePageElement: {
      prototype: HTMLHomePageElement;
      new (): HTMLHomePageElement;
    };
    

    interface HTMLPageMenuElement extends StencilComponents.PageMenu, HTMLStencilElement {}

    var HTMLPageMenuElement: {
      prototype: HTMLPageMenuElement;
      new (): HTMLPageMenuElement;
    };
    

    interface HTMLProfilePageElement extends StencilComponents.ProfilePage, HTMLStencilElement {}

    var HTMLProfilePageElement: {
      prototype: HTMLProfilePageElement;
      new (): HTMLProfilePageElement;
    };
    

    interface HTMLModalPageElement extends StencilComponents.ModalPage, HTMLStencilElement {}

    var HTMLModalPageElement: {
      prototype: HTMLModalPageElement;
      new (): HTMLModalPageElement;
    };
    

    interface HTMLPageModalElement extends StencilComponents.PageModal, HTMLStencilElement {}

    var HTMLPageModalElement: {
      prototype: HTMLPageModalElement;
      new (): HTMLPageModalElement;
    };
    

    interface HTMLNavDetailsElement extends StencilComponents.NavDetails, HTMLStencilElement {}

    var HTMLNavDetailsElement: {
      prototype: HTMLNavDetailsElement;
      new (): HTMLNavDetailsElement;
    };
    

    interface HTMLNavHomeElement extends StencilComponents.NavHome, HTMLStencilElement {}

    var HTMLNavHomeElement: {
      prototype: HTMLNavHomeElement;
      new (): HTMLNavHomeElement;
    };
    

    interface HTMLPageNavElement extends StencilComponents.PageNav, HTMLStencilElement {}

    var HTMLPageNavElement: {
      prototype: HTMLPageNavElement;
      new (): HTMLPageNavElement;
    };
    

    interface HTMLPageIndexElement extends StencilComponents.PageIndex, HTMLStencilElement {}

    var HTMLPageIndexElement: {
      prototype: HTMLPageIndexElement;
      new (): HTMLPageIndexElement;
    };
    

    interface HTMLPopoverPageElement extends StencilComponents.PopoverPage, HTMLStencilElement {}

    var HTMLPopoverPageElement: {
      prototype: HTMLPopoverPageElement;
      new (): HTMLPopoverPageElement;
    };
    

    interface HTMLPagePopoverElement extends StencilComponents.PagePopover, HTMLStencilElement {}

    var HTMLPagePopoverElement: {
      prototype: HTMLPagePopoverElement;
      new (): HTMLPagePopoverElement;
    };
    

    interface HTMLPageRangeElement extends StencilComponents.PageRange, HTMLStencilElement {}

    var HTMLPageRangeElement: {
      prototype: HTMLPageRangeElement;
      new (): HTMLPageRangeElement;
    };
    

    interface HTMLPageRefresherElement extends StencilComponents.PageRefresher, HTMLStencilElement {}

    var HTMLPageRefresherElement: {
      prototype: HTMLPageRefresherElement;
      new (): HTMLPageRefresherElement;
    };
    

    interface HTMLPageSearchbarElement extends StencilComponents.PageSearchbar, HTMLStencilElement {}

    var HTMLPageSearchbarElement: {
      prototype: HTMLPageSearchbarElement;
      new (): HTMLPageSearchbarElement;
    };
    

    interface HTMLPageSelectElement extends StencilComponents.PageSelect, HTMLStencilElement {}

    var HTMLPageSelectElement: {
      prototype: HTMLPageSelectElement;
      new (): HTMLPageSelectElement;
    };
    

    interface HTMLPageSlidesElement extends StencilComponents.PageSlides, HTMLStencilElement {}

    var HTMLPageSlidesElement: {
      prototype: HTMLPageSlidesElement;
      new (): HTMLPageSlidesElement;
    };
    

    interface HTMLPageSpinnerElement extends StencilComponents.PageSpinner, HTMLStencilElement {}

    var HTMLPageSpinnerElement: {
      prototype: HTMLPageSpinnerElement;
      new (): HTMLPageSpinnerElement;
    };
    

    interface HTMLPageTabsElement extends StencilComponents.PageTabs, HTMLStencilElement {}

    var HTMLPageTabsElement: {
      prototype: HTMLPageTabsElement;
      new (): HTMLPageTabsElement;
    };
    

    interface HTMLPageToastElement extends StencilComponents.PageToast, HTMLStencilElement {}

    var HTMLPageToastElement: {
      prototype: HTMLPageToastElement;
      new (): HTMLPageToastElement;
    };
    

    interface HTMLPageVirtualScrollElement extends StencilComponents.PageVirtualScroll, HTMLStencilElement {}

    var HTMLPageVirtualScrollElement: {
      prototype: HTMLPageVirtualScrollElement;
      new (): HTMLPageVirtualScrollElement;
    };
    

  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {
    'page-action-sheet': JSXElements.PageActionSheetAttributes;
    'page-alert': JSXElements.PageAlertAttributes;
    'page-badge': JSXElements.PageBadgeAttributes;
    'page-button': JSXElements.PageButtonAttributes;
    'page-card': JSXElements.PageCardAttributes;
    'page-checkbox': JSXElements.PageCheckboxAttributes;
    'component-preview': JSXElements.ComponentPreviewAttributes;
    'page-datetime': JSXElements.PageDatetimeAttributes;
    'page-fab': JSXElements.PageFabAttributes;
    'page-grid': JSXElements.PageGridAttributes;
    'app-list': JSXElements.AppListAttributes;
    'page-infinite-scroll': JSXElements.PageInfiniteScrollAttributes;
    'page-input': JSXElements.PageInputAttributes;
    'page-list': JSXElements.PageListAttributes;
    'page-loading': JSXElements.PageLoadingAttributes;
    'home-page': JSXElements.HomePageAttributes;
    'page-menu': JSXElements.PageMenuAttributes;
    'profile-page': JSXElements.ProfilePageAttributes;
    'modal-page': JSXElements.ModalPageAttributes;
    'page-modal': JSXElements.PageModalAttributes;
    'nav-details': JSXElements.NavDetailsAttributes;
    'nav-home': JSXElements.NavHomeAttributes;
    'page-nav': JSXElements.PageNavAttributes;
    'page-index': JSXElements.PageIndexAttributes;
    'popover-page': JSXElements.PopoverPageAttributes;
    'page-popover': JSXElements.PagePopoverAttributes;
    'page-range': JSXElements.PageRangeAttributes;
    'page-refresher': JSXElements.PageRefresherAttributes;
    'page-searchbar': JSXElements.PageSearchbarAttributes;
    'page-select': JSXElements.PageSelectAttributes;
    'page-slides': JSXElements.PageSlidesAttributes;
    'page-spinner': JSXElements.PageSpinnerAttributes;
    'page-tabs': JSXElements.PageTabsAttributes;
    'page-toast': JSXElements.PageToastAttributes;
    'page-virtual-scroll': JSXElements.PageVirtualScrollAttributes;
    }
  }

  namespace JSXElements {

    export interface PageActionSheetAttributes extends HTMLAttributes {

    }

    export interface PageAlertAttributes extends HTMLAttributes {

    }

    export interface PageBadgeAttributes extends HTMLAttributes {

    }

    export interface PageButtonAttributes extends HTMLAttributes {

    }

    export interface PageCardAttributes extends HTMLAttributes {

    }

    export interface PageCheckboxAttributes extends HTMLAttributes {

    }

    export interface ComponentPreviewAttributes extends HTMLAttributes {

    }

    export interface PageDatetimeAttributes extends HTMLAttributes {

    }

    export interface PageFabAttributes extends HTMLAttributes {

    }

    export interface PageGridAttributes extends HTMLAttributes {

    }

    export interface AppListAttributes extends HTMLAttributes {
      'items'?: any[];
    }

    export interface PageInfiniteScrollAttributes extends HTMLAttributes {

    }

    export interface PageInputAttributes extends HTMLAttributes {

    }

    export interface PageListAttributes extends HTMLAttributes {

    }

    export interface PageLoadingAttributes extends HTMLAttributes {

    }

    export interface HomePageAttributes extends HTMLAttributes {

    }

    export interface PageMenuAttributes extends HTMLAttributes {

    }

    export interface ProfilePageAttributes extends HTMLAttributes {

    }

    export interface ModalPageAttributes extends HTMLAttributes {
      'char'?: string;
    }

    export interface PageModalAttributes extends HTMLAttributes {

    }

    export interface NavDetailsAttributes extends HTMLAttributes {
      'tech'?: any;
    }

    export interface NavHomeAttributes extends HTMLAttributes {

    }

    export interface PageNavAttributes extends HTMLAttributes {

    }

    export interface PageIndexAttributes extends HTMLAttributes {
      'pages'?: any[];
    }

    export interface PopoverPageAttributes extends HTMLAttributes {
      'contentEl'?: HTMLElement;
    }

    export interface PagePopoverAttributes extends HTMLAttributes {

    }

    export interface PageRangeAttributes extends HTMLAttributes {

    }

    export interface PageRefresherAttributes extends HTMLAttributes {

    }

    export interface PageSearchbarAttributes extends HTMLAttributes {

    }

    export interface PageSelectAttributes extends HTMLAttributes {

    }

    export interface PageSlidesAttributes extends HTMLAttributes {

    }

    export interface PageSpinnerAttributes extends HTMLAttributes {

    }

    export interface PageTabsAttributes extends HTMLAttributes {

    }

    export interface PageToastAttributes extends HTMLAttributes {

    }

    export interface PageVirtualScrollAttributes extends HTMLAttributes {

    }
  }

  interface HTMLElementTagNameMap {
    'page-action-sheet': HTMLPageActionSheetElement
    'page-alert': HTMLPageAlertElement
    'page-badge': HTMLPageBadgeElement
    'page-button': HTMLPageButtonElement
    'page-card': HTMLPageCardElement
    'page-checkbox': HTMLPageCheckboxElement
    'component-preview': HTMLComponentPreviewElement
    'page-datetime': HTMLPageDatetimeElement
    'page-fab': HTMLPageFabElement
    'page-grid': HTMLPageGridElement
    'app-list': HTMLAppListElement
    'page-infinite-scroll': HTMLPageInfiniteScrollElement
    'page-input': HTMLPageInputElement
    'page-list': HTMLPageListElement
    'page-loading': HTMLPageLoadingElement
    'home-page': HTMLHomePageElement
    'page-menu': HTMLPageMenuElement
    'profile-page': HTMLProfilePageElement
    'modal-page': HTMLModalPageElement
    'page-modal': HTMLPageModalElement
    'nav-details': HTMLNavDetailsElement
    'nav-home': HTMLNavHomeElement
    'page-nav': HTMLPageNavElement
    'page-index': HTMLPageIndexElement
    'popover-page': HTMLPopoverPageElement
    'page-popover': HTMLPagePopoverElement
    'page-range': HTMLPageRangeElement
    'page-refresher': HTMLPageRefresherElement
    'page-searchbar': HTMLPageSearchbarElement
    'page-select': HTMLPageSelectElement
    'page-slides': HTMLPageSlidesElement
    'page-spinner': HTMLPageSpinnerElement
    'page-tabs': HTMLPageTabsElement
    'page-toast': HTMLPageToastElement
    'page-virtual-scroll': HTMLPageVirtualScrollElement
  }

  interface ElementTagNameMap {
    'page-action-sheet': HTMLPageActionSheetElement;
    'page-alert': HTMLPageAlertElement;
    'page-badge': HTMLPageBadgeElement;
    'page-button': HTMLPageButtonElement;
    'page-card': HTMLPageCardElement;
    'page-checkbox': HTMLPageCheckboxElement;
    'component-preview': HTMLComponentPreviewElement;
    'page-datetime': HTMLPageDatetimeElement;
    'page-fab': HTMLPageFabElement;
    'page-grid': HTMLPageGridElement;
    'app-list': HTMLAppListElement;
    'page-infinite-scroll': HTMLPageInfiniteScrollElement;
    'page-input': HTMLPageInputElement;
    'page-list': HTMLPageListElement;
    'page-loading': HTMLPageLoadingElement;
    'home-page': HTMLHomePageElement;
    'page-menu': HTMLPageMenuElement;
    'profile-page': HTMLProfilePageElement;
    'modal-page': HTMLModalPageElement;
    'page-modal': HTMLPageModalElement;
    'nav-details': HTMLNavDetailsElement;
    'nav-home': HTMLNavHomeElement;
    'page-nav': HTMLPageNavElement;
    'page-index': HTMLPageIndexElement;
    'popover-page': HTMLPopoverPageElement;
    'page-popover': HTMLPagePopoverElement;
    'page-range': HTMLPageRangeElement;
    'page-refresher': HTMLPageRefresherElement;
    'page-searchbar': HTMLPageSearchbarElement;
    'page-select': HTMLPageSelectElement;
    'page-slides': HTMLPageSlidesElement;
    'page-spinner': HTMLPageSpinnerElement;
    'page-tabs': HTMLPageTabsElement;
    'page-toast': HTMLPageToastElement;
    'page-virtual-scroll': HTMLPageVirtualScrollElement;
  }
}
declare global { namespace JSX { interface StencilJSX {} } }

