/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface ComponentPreview {

    }
  }

  interface HTMLComponentPreviewElement extends StencilComponents.ComponentPreview, HTMLStencilElement {}

  var HTMLComponentPreviewElement: {
    prototype: HTMLComponentPreviewElement;
    new (): HTMLComponentPreviewElement;
  };
  interface HTMLElementTagNameMap {
    'component-preview': HTMLComponentPreviewElement;
  }
  interface ElementTagNameMap {
    'component-preview': HTMLComponentPreviewElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'component-preview': JSXElements.ComponentPreviewAttributes;
    }
  }
  namespace JSXElements {
    export interface ComponentPreviewAttributes extends HTMLAttributes {

    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
